let
	StartDate = Text.From(ReportDate[Date]{0}),
SQL =
"SELECT
    'BCU' AS SOURCE, 
	WH_ACCTCOMMON.ACCTNBR,
	BalSubAcct.SUBACCTNBR, 
	WH_ACCTCOMMON.EFFDATE, 
	WH_ACCTCOMMON.MJACCTTYPCD, 
	WH_ACCTCOMMON.NOTEBAL, 
	WH_ACCTCOMMON.CURRACCTSTATCD, 
	WH_ACCTCOMMON.CURRMIACCTTYPCD,
	WH_ACCTCOMMON.PRODUCT,
	BalSubAcct.BALCATCD,
	BalSubAcct.BALTYPCD,
	MJMIACCTTYP.CURRENCYCD,
	CEIL(MONTHS_BETWEEN(ACCT.DATEMAT, TO_DATE('"&StartDate&"','MM/DD/YYYY'))) AS RemainingAmortization,
	WH_ACCTCOMMON.TAXRPTFORPERSNBR,
	WH_ACCTCOMMON.TAXRPTFORORGNBR
FROM WH_ACCTCOMMON
LEFT OUTER JOIN 
	(SELECT
		ACCTNBR,
		SUBACCTNBR,
		BALCATCD,
		BALTYPCD
	FROM ACCTSUBACCT
	WHERE BALTYPCD = 'BAL'
		AND BALCATCD = 'NOTE')
	BalSubAcct
	ON WH_ACCTCOMMON.ACCTNBR = BalSubAcct.ACCTNBR
INNER JOIN ACCT
	ON WH_ACCTCOMMON.ACCTNBR = ACCT.ACCTNBR
LEFT OUTER JOIN MJMIACCTTYP
	ON WH_ACCTCOMMON.MJACCTTYPCD = MJMIACCTTYP.MJACCTTYPCD
	AND WH_ACCTCOMMON.CURRMIACCTTYPCD = MJMIACCTTYP.MIACCTTYPCD          
WHERE WH_ACCTCOMMON.EFFDATE = TO_DATE('"&StartDate&"', 'MM/DD/YYYY')
	AND WH_ACCTCOMMON.NOTEBAL > 0
	AND WH_ACCTCOMMON.MJACCTTYPCD IN ('CK', 'SAV', 'TD')
	AND WH_ACCTCOMMON.CURRMIACCTTYPCD NOT IN ('ECSC', 'ECSM', 'FCSC', 'FCSM')"
in
	SQL
