let
    BCUSource = Oracle.Database("BCUDatabase", [Query=
        "SELECT
            'BCU' AS SOURCE,
            MJMIACCTGL.MJACCTTYPCD,
	    MJMIACCTGL.MIACCTTYPCD,
	    MJMIACCTGL.BALCATCD,
	    MJMIACCTGL.BALTYPCD,
	    GLACCTTITLE.GLACCTTITLENAME,
	    SUBSTR(GLACCT.XREFGLACCTNBR, 0, 8) AS GLNUM,
	    SUBSTR(GLACCT.XREFGLACCTNBR, -3) AS COSTCENTER
        FROM MJMIACCTGL
	    INNER JOIN GLACCT
		ON MJMIACCTGL.GLACCTTITLENBR = GLACCT.GLACCTTITLENBR
	    INNER JOIN GLACCTTITLE
		ON MJMIACCTGL.GLACCTTITLENBR = GLACCTTITLE.GLACCTTITLENBR
        WHERE MJMIACCTGL.BALTYPCD = 'BAL'
        /*WHERE (MJMIACCTGL.MJACCTTYPCD NOT IN ('CK', 'SAV')
            AND MJMIACCTGL.BALTYPCD = 'BAL'
	    AND MJMIACCTGL.BALCATCD = 'NOTE')
        OR (MJMIACCTGL.MJACCTTYPCD IN ('CK', 'SAV')
            AND MJMIACCTGL.BALTYPCD = 'BAL'
	    AND MJMIACCTGL.BALCATCD = 'LMOD')
        OR MJMIACCTGL.MJACCTTYPCD IN ('CK', 'SAV')
            AND MJMIACCTGL.BALTYPCD = 'BAL'
	    AND MJMIACCTGL.BALCATCD = 'ODEX'*/"]),
    RCCUSource = Oracle.Database("RCCUDatabase", [Query=
        "SELECT
            'RCCU' AS SOURCE,
            MJMIACCTGL.MJACCTTYPCD,
	    MJMIACCTGL.MIACCTTYPCD,
	    MJMIACCTGL.BALCATCD,
	    MJMIACCTGL.BALTYPCD,
	    GLACCTTITLE.GLACCTTITLENAME,
	    SUBSTR(GLACCT.XREFGLACCTNBR, 0, 8) AS GLNUM,
	    SUBSTR(GLACCT.XREFGLACCTNBR, -3) AS COSTCENTER
        FROM MJMIACCTGL
	    INNER JOIN GLACCT
		ON MJMIACCTGL.GLACCTTITLENBR = GLACCT.GLACCTTITLENBR
	    INNER JOIN GLACCTTITLE
		ON MJMIACCTGL.GLACCTTITLENBR = GLACCTTITLE.GLACCTTITLENBR
        WHERE MJMIACCTGL.BALTYPCD = 'BAL'
        /*WHERE (MJMIACCTGL.MJACCTTYPCD NOT IN ('CK', 'SAV')
            AND MJMIACCTGL.BALTYPCD = 'BAL'
	    AND MJMIACCTGL.BALCATCD = 'NOTE')
        OR (MJMIACCTGL.MJACCTTYPCD IN ('CK', 'SAV')
            AND MJMIACCTGL.BALTYPCD = 'BAL'
	    AND MJMIACCTGL.BALCATCD = 'LMOD')
        OR MJMIACCTGL.MJACCTTYPCD IN ('CK', 'SAV')
            AND MJMIACCTGL.BALTYPCD = 'BAL'
	    AND MJMIACCTGL.BALCATCD = 'ODEX'*/"]),
    ABCUSource = Table.Combine({BCUSource, RCCUSource}),
    #"Changed Type" = Table.TransformColumnTypes(ABCUSource,{{"COSTCENTER", type number}, {"GLNUM", type number}}),
    #"Removed Duplicates" = Table.Distinct(#"Changed Type")
in
    #"Removed Duplicates"